### ISSUE TITLE
Support for Multiple Constraints on Vehicle Capacity

### ISSUE THREAD

**Issue by hxrshu** [inria-UFF/VRPSolverEasy#18]
Hi,

I am researching on a particular vehicle routing problem where the vehicle has two types of constraints -- one, a constraint on how many units can be loaded, and second, the total weight. Might it be possible to incorporate this second constraint on the vehicle capacity within VRPSolverEasy? Any inputs/guidance on how to approach this would be appreciated :)

**Comment by rrsadykov** [comment]
If you do not have time windows, you can use time as the weight resource (you define time windows [0, max weight] and transition time equal to the weight of the customer your are going to ). Otherwise, this problem cannot be solved with VRPSolverEasy. 

However, it can be easily formulated as the standard VRPSolver model. VRPSolver can be used via a Julia interface (https://github.com/inria-UFF/BaPCodVRPSolver.jl) or a C++ interface (https://bapcod.math.u-bordeaux.fr/). 

If there will be other request for the feature, we may consider adding additional resources to VRPSolverEasy.

**Comment by rrsadykov** [comment]
I close this issue now, but we will take note about the feature requested. Thank you for your interest in our solver

**Comment by rrsadykov** [comment]
Nice to hear! Thanks for reporting
