### ISSUE TITLE
Is bapcod a sequential solver or a parallel solver?

### ISSUE THREAD

**Issue by dxyzx0** [inria-UFF/VRPSolverEasy#21]
Thank you for your great work and sorry for bringing up this naive question. 

I've tested several problems only found one cpu is at 100% usage. Is bapcod designed as a sequential solver or it's just my problems are too easy such that they are all solved at the root?

If bapcod is desgined so, could you elaborate a little why you did not try to implement it as a parallel solver? It seems there are no issue in the algorithm design.

**Comment by rrsadykov** [comment]
Thank you for your feedback!

Yes, BaPCod is a sequential solver. Underlying MIP and LP solvers can be run with multiple threads, but VRPSolverEasy always parameterises them to run in a single thread. 

Of course, it would be great to make the solver parallel, but it is far from trivial to have a decent speed-up from parallelisation, as most of the time is spent in LP solver or in the labelling algorithm when solving the pricing problems. There is no yet parallel LP solvers on the market with decent speed-ups (or even with speed-ups at all).  One may of course solve pricing subproblems in parallel, it is relatively easy to implement, but most of the time the pricing time is dominated by one subproblem (at least for VRPs). Also, it would be a large effort to implement a good parallel labelling algorithm. 

The main uses of BaPCod and VRPSolver are in academia, i.e., to publish papers. It is very hard to have a good paper on  parallel implementation, as scientifically it is not very much novel. Thus "effort/outcome" ratio is too large.  In addition, as the problems we solve are NP-hard, i.e. they intrinsically attain combinatorial explosion at some point, it pays more to try to devise methods and techniques which bring you an exponential speed-up rather than linear speed-up from parallelisation.

**Comment by dxyzx0** [comment]
Thanks a lot for quick response. I agree with you on that most time is spent on LP, so you are trying to argue that it is hard to make LP parallel. But in my mind, VRP is a combinatorial problem, so it is reasonable to parallelize the branch and bound algorithm, right?

**Comment by rrsadykov** [comment]
Yes, you are right, branch-and-bound part is where the parallelisation is expected to bring a significant speed-up. So, the main reason for not doing it is that there are very few people who really master BaPCod and there is not enough time to this task (which is again not "profitable" in terms of research output). Also, BaPCod is ~20 years old and it was not implemented with parallelisation in mind right from the start. Thus parallelisation is great endeavor to do.

**Comment by dxyzx0** [comment]
Oh, I just read your paper published on math programming 2020, which makes think it is a new solver. Maybe I should read it more carefully. hhh

**Comment by rrsadykov** [comment]
VRPSolver can be seen as a layer (actually two, above and below) over BaPCod, which is relatively old.

**Comment by dxyzx0** [comment]
Thanks a lot.

Additional question: Is there any doc about the layers added by VRPSolverEasy? I mean what does VRPSolverEasy do to the bapcod solver? It defines a new branching rule or a RCSP solver?

**Comment by rrsadykov** [comment]
I close as no more activity in this issue.
