### ISSUE TITLE
How do I get HFVRP to run?

### ISSUE THREAD

**Issue by mventura00** [inria-UFF/VRPSolverEasy#4]
I'm fairly new to this, although I was able to get CVRP to run well on my laptop.

For HFVRP, at the botton in main() , it requires :
-time
-solver name
-instance path
-path solver

BUt I have no idea what this means? What is an instance path? 
How can I get the program to run? 
Thanks!!
Marta

**Comment by najibprog** [comment]
Dear Marta,

Thank you for your interest in our solver. If you want to run an instance of HFVRP, you can 

- go to the folder containing `HFVRP.py` 
- open the command prompt and specify your parameters like this: 

![Screenshot 2023-06-22 150834](https://github.com/inria-UFF/VRPSolverEasy/assets/60361177/0e36699c-4ca4-4081-a107-8309a0788335)

- each demo expects a different instance format, so, you should check the compatibility of your instance with the demo.

**Comment by mventura00** [comment]
I was able to get VRPsolvereasy to run using a high-performance computing cluster at my university. I tried putting 30,000 (time limit) which is 8hr 20 min, but it was not enough. Now I am trying double that time and hopefully it will be enough... How long is a normal time for it to run (I know it depends on computer processing power etc)? 

Another question. I used this dataset (that I pulled from your GitHub : demo/data/HFVRP). See file attached. 
In the first line, the '100' represents the 100 cities to deliver goods to, correct?
I can see (lines 2 - lines 102) shows:  id#, lat, long, and demand # .... where the first one on (line 2) is for the depot, and (lines 3-102) are the 100 other cities. Is this correct? 
Then the last few lines, where line 103: shows '3' means there are 3 different sized trucks. 
(Lines 104-106) , where each line has the capacity at the truck in the beginning, but what are the other 3 numbers. For instance, on line 104: I see truck capacity = 100. Then what is the 500, 1.0, 0, 100, represent? 
Is this all defined somewhere in some document? I did not see it specified in detail in the HAL open science paper.

**Comment by rrsadykov** [comment]
Dear Marta @mventura00, 

One cannot predict the solution time, as the underlying problem is NP-hard. Some instances will be solved to optimality within your time limit, some will not. Some instances will be simply unsolvable within any reasonable time limit.

About the format of data files for the HFVRP, you description of the first line and the customer lines are correct. For the last three lines (they indeed describe the vehicle types), we have:

`<vehicle capacity> <fixed cost for using one vehicle of this type> <variable cost factor>  <min number of vehicles of this type to use> <max number of vehicles of this type to use>`

where variable cost factor is the multiplier for the distance covered by vehicles of this type in the objective function (i.e., the larger is the vehicle, the larger will be its fuel consumption).

Hope this helps, 
Ruslan

**Comment by mventura00** [comment]
Dear @rrsadykov 
Thank you so very much! You are the best! This is exactly the answer I was looking for in terms of what information I need to provide for the heterogenous Freight VRP (the last few lines) of the input code. Thank you for taking the time and patience  to explain even what the 'variable cost factor' considers  (is the multiplier for the distance covered - I imagine related to the gas mileage consuption $ cost per mile) and how the larger is the vehicle, the larger will be it's fuel consumption (for this, I will look online for some specific data or information related to this!). Thanks again and yes, this did help me so much.
Marta
